SMARTY_AUTH_ID: "cc5d64ad-b025-c32a-b258-85386ab89678"
SMARTY_AUTH_TOKEN: "OPH7pOoUwQh7a680WXhT"

CONGRESS_API_KEY: "DSklwTs6CC11pRkze5KER8NLkM4HAghb8sT27cQ2"
GOOGLE_API_KEY: "AIzaSyB-aTcwso-m26B67yJTO3mEkqm9J6jzSDo"
OPENSECRETS_API_KEY: "78e3003fb31d85426eb8dcc57aa4f647"
